-- phpMyAdmin SQL Dump
-- version 4.1.8
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Sep 09, 2014 at 12:07 PM
-- Server version: 5.5.32-cll-lve
-- PHP Version: 5.4.23

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `dbmain`
--

-- --------------------------------------------------------

--
-- Table structure for table `admin_details`
--

DROP TABLE IF EXISTS `admin_details`;
CREATE TABLE IF NOT EXISTS `admin_details` (
  `username` varchar(15) NOT NULL,
  `password` varchar(32) NOT NULL,
  `api_user` varchar(15) NOT NULL,
  `api_pass` varchar(20) NOT NULL,
  `balance` int(4) NOT NULL,
  PRIMARY KEY (`username`),
  UNIQUE KEY `api_user` (`api_user`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `admin_details`
--

INSERT INTO `admin_details` (`username`, `password`, `api_user`, `api_pass`, `balance`) VALUES
('jintamary', 'aa7283a0b124df5b33348b5073dcc9f5', 'jintamary', 'Hack2H377**', 900),
('safa', 'aa7283a0b124df5b33348b5073dcc9f5', 'safa', 'Hack2H377**', 900),
('saff', 'aa7283a0b124df5b33348b5073dcc9f5', 'saff', 'Hack2H377**', 900),
('santhanu', 'aa7283a0b124df5b33348b5073dcc9f5', 'santhanu', 'Hack2H377**', 900),
('sarath2610', 'aa7283a0b124df5b33348b5073dcc9f5', 'sarath2610', 'Hack2H377**', 900),
('Stenal Hacker', 'aa7283a0b124df5b33348b5073dcc9f5', 'stenalhacker', 'Hack2H377**', 900),
('stenalpjolly', 'aa7283a0b124df5b33348b5073dcc9f5', 'stenalpjolly', 'Hack2H377**', 900);

-- --------------------------------------------------------

--
-- Table structure for table `questions_assigned`
--

DROP TABLE IF EXISTS `questions_assigned`;
CREATE TABLE IF NOT EXISTS `questions_assigned` (
  `serialID` int(10) NOT NULL AUTO_INCREMENT,
  `email` varchar(30) NOT NULL,
  `questionID` int(6) NOT NULL,
  `level` int(2) NOT NULL,
  `status` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`serialID`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=272 ;

--
-- Dumping data for table `questions_assigned`
--

INSERT INTO `questions_assigned` (`serialID`, `email`, `questionID`, `level`, `status`) VALUES
(230, 'stenalpjolly@gmail.com', 11, 1, 0),
(231, 'stenalpjolly@gmail.com', 26, 1, 0),
(232, 'stenalpjolly@gmail.com', 28, 1, 0),
(233, 'stenalpjolly@gmail.com', 8, 1, 0),
(234, 'stenalpjolly@gmail.com', 13, 1, 0),
(235, 'stenalpjolly@gmail.com', 12, 1, 0),
(236, 'stenalpjolly@gmail.com', 24, 1, 0),
(237, 'stenalpjolly@gmail.com', 35, 1, 0),
(238, 'stenalpjolly@gmail.com', 7, 1, 0),
(239, 'stenalpjolly@gmail.com', 17, 2, 0),
(240, 'stenalpjolly@gmail.com', 40, 2, 0),
(241, 'stenalpjolly@gmail.com', 14, 2, 0),
(242, 'stenalpjolly@gmail.com', 41, 2, 0),
(243, 'stenalpjolly@gmail.com', 16, 2, 0),
(244, 'stenalpjolly@gmail.com', 37, 2, 0),
(245, 'stenalpjolly@gmail.com', 31, 3, 0),
(246, 'stenalpjolly@gmail.com', 3, 4, 0),
(247, 'stenalpjolly@gmail.com', 27, 3, 0),
(248, 'stenalpjolly@gmail.com', 2, 4, 0),
(249, 'stenalpjolly@gmail.com', 34, 3, 0),
(250, 'stenalpjolly@gmail.com', 20, 4, 0),
(251, '', 26, 1, 0),
(252, '', 35, 1, 0),
(253, '', 4, 1, 0),
(254, '', 5, 1, 0),
(255, '', 12, 1, 0),
(256, '', 10, 1, 0),
(257, '', 7, 1, 0),
(258, '', 30, 1, 0),
(259, '', 13, 1, 0),
(260, '', 39, 2, 0),
(261, '', 41, 2, 0),
(262, '', 29, 2, 0),
(263, '', 16, 2, 0),
(264, '', 17, 2, 0),
(265, '', 21, 2, 0),
(266, '', 33, 3, 0),
(267, '', 19, 4, 0),
(268, '', 23, 3, 0),
(269, '', 1, 4, 0),
(270, '', 34, 3, 0),
(271, '', 20, 4, 0);

-- --------------------------------------------------------

--
-- Table structure for table `questions_input`
--

DROP TABLE IF EXISTS `questions_input`;
CREATE TABLE IF NOT EXISTS `questions_input` (
  `qusID` int(6) NOT NULL AUTO_INCREMENT,
  `qusName` varchar(25) NOT NULL,
  `question` varchar(4000) NOT NULL,
  `sample_input` text NOT NULL,
  `input` text NOT NULL,
  `sample_output` text NOT NULL,
  `output` text NOT NULL,
  `mark` int(5) DEFAULT NULL,
  `level` int(2) NOT NULL DEFAULT '1',
  `input_desc` text,
  `output_desc` text,
  `pdf_link` varchar(80) DEFAULT NULL,
  PRIMARY KEY (`qusID`),
  UNIQUE KEY `qusName` (`qusName`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=42 ;

--
-- Dumping data for table `questions_input`
--

INSERT INTO `questions_input` (`qusID`, `qusName`, `question`, `sample_input`, `input`, `sample_output`, `output`, `mark`, `level`, `input_desc`, `output_desc`, `pdf_link`) VALUES
(1, 'Herding Frosh', 'One day, a lawn in the centre of campus became infested with Frosh. In an effort to beautify the campus, one of our illustrious senior classmen decided to round them up using a length of pink silk. Your job is to compute how much silk was required to complete the task.<br/>\r\nThe senior classman tied the silk to a telephone post, and walked around the perimeter of the area containing the Frosh, drawing the silk taught so as to encircle all of them. He then returned to the telephone post. The senior classman used the minimum amount of silk necessary to encircle all the frosh plus one extra metre at each end to tie it.<br/>\r\nYou may assume that the telephone post is at coordinates (0,0), where the first dimension is North/South and the second dimension is East/West. The coordinates of the Frosh are given in metres relative to the post. There are no more than 1000 Frosh.\r\n', '', '1\r\n\r\n4\r\n1', '', '10.83', 20, 4, 'The input begins with a single positive integer on a line by itself indicating the number of the cases following, each of them as described below. This line is followed by a blank line, and there is also a blank line between two consecutive inputs.\r\nThe input consists of a line specifying the number of Frosh, followed by one line per Frosh with two real numbers his or her position.\r\n', 'For each test case, the output must follow the description below. The outputs of two consecutive cases will be separated by a blank line.\r\nThe output consists of a single number - the length of silk in metres, to two decimal places.\r\n', '704.pdf'),
(2, '{sum+=i++} to Reach N', 'All the positive numbers can be expressed as a sum of one, two or more consecutive positive integers. For example 9 can be expressed in three such ways, 2+3+4, 4+5 or 9. Given an integer less than (9*10^14+1) or (9E14 + 1) or (9*1014 +1) you will have to determine in how many ways that number can be expressed as summation of consecutive numbers.', '9<br/>\r\n11<br/>\r\n', '9\r\n11\r\n12\r\n', '3<br/>\r\n2<br/>\r\n', '3\r\n2\r\n2\r\n', 20, 4, 'The input file contains less than 1100 lines of input. Each line contains a single integer N  (0<=N<= 9E14). Input is terminated by end of file', 'For each line of input produce one line of output. This line contains an integer which tells in how many ways N can be expressed as summation of consecutive integers.', '704.pdf'),
(3, 'Prince Frog', 'Long ago, there was a monster living in Adventure Castle of Magic. One day he saw the prince Infant Concord and his wife PrincessCharm living a sweet life. He was very jealous. So the monster used his powerful magic and turned the prince into a frog.\r\n<br/>\r\nThe brave and smart princess made her mind to save her husband with all her efforts. Having overcome thousands of difficulties and challenges, she finally arrived at the Adventure Castle of Magic. Unfortunately, the handsome prince she loved deeply was transformed to an ugly and awful frog by the curse of the monster. The monster gave her a very hard puzzle, which he thought to be a mission impossible as a condition to exchange the prince.\r\n<br/> \r\nThe princess was required to choose a magic rope from two ones. One of them would create knots by drawing the stringâ€™s ends, on the contrary, the other wouldnâ€™t. If the princess chose the right one, the curse would disappear and the price would be rescued, otherwise he would be strangled to death. In order to rescue her lover, without hesitate, the princess accepted the challenge. My dear friends, you must wish the princess could solve the problem successfully. Now the princess needs your help to beat the monster. Use your clever brain and think about this difficult trick. Make use of your programming skills to help the princess to make the correct choice\r\n<br/>', '1<br/>\r\n+1 -1 0<br>', '5\r\n+1 -1 0\r\n-1 -2 -3', 'Case 1: No', 'Case 1: No\r\nCase 2: ', 20, 4, 'The first line contains the number of tests t(1<=t<=15). Each case contains exactly one line.\r\n<br/>\r\nWe describe the rope by pointing out the cross -point (See figure (c)). We first number all the cross-point. Then, our finger go along the rope from one end to the other, whenever we encounter a cross-point we will record its number on the paper. If the rope goes above the point, we write down a positive number. If the rope goes under the point, we write down a negative number. In the end, we put a zero as an end sign.\r\n<br/>\r\nFor example, the rope shown in figure (c) is recorded as:<br/>\r\n+1 -2 +3 -4 +5 -6 -7 +8 +2 -1 -10 +9 -8 -3 +4 -5 +6 +7 -9 +10 0<br/>\r\n', 'For each test case, print the case number and the your answer. If the rope will make a knot by drawing the stringâ€™s ends, please output â€œYesâ€. Otherwise, output â€œNoâ€.', '704.pdf'),
(4, 'Longest Substring', 'Rahul went to an interview and the first question was to write a program to find the longest substring without repeating characters. He had no idea how to do it.Can you help him..?', '2<br/>\r\nabcabcbb<br/>\r\nTakshak<br/>', '3\r\nHelipcopters\r\njava_java_java_java\r\nTakshak', 'cab,abc,bca<br/>\r\nTaksh<br/>\r\n', 'lipcopters\r\n_jav,va_j\r\nTaksh\r\n', 5, 1, 'First line will be number of test cases followed by the input strings. ', 'Output of each test case will be printed in line by line.', '704.pdf'),
(5, 'Reverse String', 'Write a program to reverse all the words in the string', '2<br/>\r\nTHIS IS CODEIT.<br/>\r\nMALAYALAM<br/>', '2\r\nMY NAME IS PROGRAM.\r\nWELCOME TO TAKSHAK.', 'SIHT SI TIEDOC.<br/>\r\nMALAYALAM<br/>\r\n', 'YM EMAN SI MARGORP.\r\nEMOCLEW OT KAHSKAT.', 5, 1, 'First number of input cases will be given followed by the Strings. Each string is separated by dot and new line.', 'Output should be in the same order as of input.', 'Temp'),
(7, 'Duplicate Remove', 'Write a program to remove all the duplicate elements from the string', '1<br/>\r\nRemover<br/>', '2\r\nEngineering\r\nTakshak', 'mov<br/>', 'r\r\nTsh', 5, 1, 'First number of input cases will be given followed by the Strings. Each string is separated by dot and new line.', 'Output should be in the same order as of input.', 'Temp'),
(8, 'Longest Consecutive', 'Given an unsorted array of integers, find the length of the longest consecutive elements sequence', '4 1 2 3 4', '7 100 4 200 0 1 2 3', '4', '4', 5, 1, 'First length of array will be given followed by integer array.', 'Display the output.', 'Temp'),
(9, 'PALINDROMIC ', 'Write a program to print the longest PALINDROMIC substring', '1<br/>\r\nMalayalam.', '2\r\ndad.\r\nNice ec.', 'alayala.', 'dad.\r\nce ec.', 5, 1, 'First number of input cases will be given followed by the Strings. Each string is separated by dot and new line.', 'Output should be in the same order as of input.', 'Temp'),
(10, 'Palindrome Partition ', 'Given a string s, partition s such that every substring of the partition is a palindrome', '1<br/>\r\nCODEIT.', '2\r\nMALAYALAM.\r\nHAI.\r\n', 'C O D E I T.<br/>', 'MALAYALAM.\r\nH A I.', 5, 1, 'First number of input cases will be given followed by the Strings. Each string is separated by dot and new line.', 'Output should be in the same order as of input.', 'Temp'),
(11, 'Fibonacci Range', 'Given two numbers a and b, calculate how many Fibonacci numbers are in the range [a, b].\r\n', '10 100</br>\r\n0 0<br/>', '10 100\r\n1234567890 9876543210\r\n0 0\r\n', '5', '5\r\n4\r\n', 5, 1, 'The input contains several test cases. Each test case consists of two non-negative integer numbers a and b. Input is terminated by a = b = 0. Otherwise, a â‰¤ b â‰¤ 10100. The numbers a and b are given with no superfluous leading zeros.\r\n', 'For each test case output on a single line the number of Fibonacci numbers fi with a â‰¤ fi â‰¤ b.\r\n', 'Temp'),
(12, 'Typing Error', 'A common typing error is to place your hands on the keyboard one row to the right\r\nof the correct position. Then â€œQâ€ is typed as â€œWâ€ and â€œJâ€ is typed as â€œKâ€ and so on.\r\nYour task is to decode a message typed in this manner.\r\n', 'VPFR OY/', 'O S, GOMR YPFSU/', 'CODE IT.', 'I AM FINE TODAY.', 5, 1, 'Input consists of several lines of text. Each line may contain digits, spaces, uppercase\r\nletters (except â€œQâ€, â€œAâ€, â€œZâ€), or punctuation shown above [except back-quote (â€˜)].\r\nKeys labeled with words [Tab, BackSp, Control, etc.] are not represented in the input.\r\n', 'You are to replace each letter or punctuation symbol by the one immediately to its left\r\non the QWERTY keyboard shown above. Spaces in the input should be echoed in the\r\noutput.\r\n', 'Temp'),
(13, 'Function', 'n 1 2 3 4 5 6 7 8 9 10 11 12 <br/>\r\nf(n) 1 2 2 3 3 4 4 4 5 5 5 6 <br/>\r\nIn this problem you are expected to write a program that calculates the value of f(n) given the value of n.\r\n', '100<br/>\r\n9999<br/>\r\n0<br/>\r\n', '100\r\n9999\r\n123456\r\n1000000000\r\n0\r\n', '21<br/>\r\n356<br/>', '21\r\n356\r\n1684\r\n438744\r\n', 5, 1, 'The input may contain multiple test cases. Each test case occupies a separate line and\r\ncontains an integer n (1 â‰¤ n â‰¤ 2, 000, 000, 000). The input terminates with a test case\r\ncontaining a value 0 for n and this case must not be processed.\r\n', 'For each test case in the input, output the value of f(n) on a separate line.', 'Temp'),
(14, 'Packets ', 'A factory produces products packed in square packets of the same height h and of the sizes 1*1,2*2,3*3,4*4,5*5,6*6. These products are always delivered to customers in the square parcels of the same height h as the products have and of the size 6*6. Because of the expenses it is the interest of the factory as well as of the customer to minimize the number of parcels necessary to deliver the ordered products from the factory to the customer. A good program solving the problem of finding the minimal number of parcels necessary to deliver the given products according to an order would save a lot of money. You are asked to make such a program.', '0 0 4 0 0 1 <br/>\r\n7 5 1 0 0 0 <br/>\r\n0 0 0 0 0 0 <br/>', '', '2 <br/>\r\n1\r\n', '', 10, 2, 'The input file consists of several lines specifying orders. Each line specifies one order. Orders are described by six integers separated by one space representing successively the number of packets of individual size from the smallest size 1*1 to the biggest size 6*6 . The end of the input file is indicated by the line containing six zeros.', 'The output file contains one line for each line in the input file. This line contains the minimal number of parcels into which the order from the corresponding line of the input file can be packed. There is no line in the output file corresponding to the last ``null'' line of the input file.', 'Temp'),
(16, 'GAMBLING GRINGOTTS', 'Gambling fascinates every single person. Here letâ€™s try a new style of gamblingâ€¦â€¦\r\nIn gringott, every player can choose one card from a range of values. the game progress as belowâ€¦. \r\nn represent the money pinned on the cardâ€¦â€¦\r\nInput n\r\nIf n is even, n=n/2;\r\nIf n is odd,n=3n+1\r\nRepeat above 2 steps until n=1\r\nFor eg: if n is 22 then it goes as below:\r\n22 11 34 17 52 26 13 40 20 10 5 16 8 4 2 1\r\nFor each new n he gets a new card of that value. The life cycle depends on the number of cards he has at the end of the game. And his return is sum of the values in all cards he has with him. \r\nNow we have a real problem. Rithesh is one who is crazy about this gambling and he is really rich. He is so rich that he select 2 cards and play with any value in between the two, inclusive of both. So we help him find the value that will give him maximum returns and the maximum life cycle (value within the selected range). \r\n', '1 10 <br/>\r\n\r\n\r\n', '1 10\r\n100 200\r\n', '1 10 20\r\n', '1 10 20\r\n100 200 125\r\n', 10, 2, 'i and j', 'i    j    max. life cycle\r\nHelp rithesh in this!!!!!!!\r\n', 'Temp'),
(17, 'Jolly Jumpers', 'A sequence of n > 0 integers is called a jolly jumper if the absolute values of the difference between successive elements take on all the values 1 through n-1. For instance,\r\n1 4 2 3\r\nis a jolly jumper, because the absolutes differences are 3, 2, and 1 respectively. The definition implies that any sequence of a single integer is a jolly jumper. You are to write a program to determine whether or not each of a number of sequences is a jolly jumper.\r\n', '4 1 4 2 3 <br/>\r\n5 1 4 2 -1 6\r\n', '19 22 24 21', 'Jolly <br/>\r\nNot jolly\r\n', 'Not Jolly', 10, 2, 'Each line of input contains an integer n <= 3000 followed by n integers representing the sequence.', 'For each line of input, generate a line of output saying "Jolly" or "Not jolly".', 'Temp'),
(19, 'Square root', 'You are to determinate X by given Y, from expression  ', '1\r\n\r\n72064037814900\r\n', '1\r\n\r\n7206604678144\r\n', '8489054', '2684512', 20, 4, 'The first line is the number of test cases, followed by a blank line.<br/>\r\nEach test case of the input contains a positive integer Y (1<=Y<=101000), with no blanks or leading zeroes in it.<br/>\r\nIt is guaranteed, that for given Y, X will be always an integer.<br/>\r\nEach test case will be separated by a single line.<br/>\r\n', 'For each test case, your program should print X in the same format as Y was given in input.<br/>\r\nPrint a blank line between the outputs for two consecutive test cases<br/>\r\n', 'Temp'),
(20, 'The Hazard of CSE Departm', 'From a given point A, a person covered a certain distance d in a certain direction and reached a point B and then he maintained that direction and reached a point C after he had covered a distance e. Then he came back to point A and did the same thing covering the same amount of distances in each step but may or may not be in another direction and got two similar points D and E.  Here, D is similar to B and E is similar to C. The point C, D and B, E are then connected. CD and BE intersects at a point P (or in some case on a line P). The problem is that after one week that person forgot if the distance e was measured from A or from B (in case of the second journey point D). He remembered one thing that in both cases he followed the same strategy. He also discovered that if e<d he could assume that the distance was not measured from A but in other cases he was unsure. Given the equation of the line AC and AE and the value of d and e you will have to determine the equation of the line AP (if possible). When there are infinite numbers of AP the determination of AP is impossible. The determination of the equation of AP is also impossible when point A is at infinite distance. Keep one thing in mind that the alphabetic symbols of this questions are case sensitive. That is A and a are not the same. One of the angles between the two walking directions will be less than 180 degree.', '1<br/>\r\n1 0 0<br/>\r\n0 1 0<br/>\r\n10 20<br/>\r\n', '2\r\n1 0 0\r\n0 1 0\r\n10 20\r\n1 2 3\r\n4 5 6\r\n0 0\r\n', '1.000 -1.000 0.000<br/>\r\n1.000 1.000 0.000<br/>\r\n', '1.000 -1.000 0.000\r\n1.000 1.000 0.000\r\nEquation not found.\r\n', 20, 4, 'The input contains and integer N at first, which is the number of test cases, then followed by N test cases. Each test case contains two lines with three integers and one line with two integers. The two lines with three integers contain the integers p, q, r and s, t, u(-1000>= p, q, r, s, t, u <=1000) respectively where the Equation of   AC is px + qy + r = 0 and the equation of AE is sx + ty + u = 0and the last line with two integers are the values d (d>=0 & d<=1000) and e (e>=0 & e<=1000).', 'For each line of input output the coefficients of the equation of AP. The equation is of the form x + by + c = 0 (when the absolute value of the coefficient of x is greater than the absolute value of the coefficient of y or even equal) or of the form ax + y + c = 0 (in other cases). The output will be in floating point format with three digits after the decimal. If the Equation of AP is not determinable print the line â€œEquation not found.â€ As a line denotes two directions so you may be confused which direction to take. In that case you may get finite numbers of equations of AP. Print all those equations according to the rule specified above, according to the sample output and in ascending order of their slopes. The numbers in the output are separated by a single space.', 'Temp'),
(21, 'Repackaging(10089)', 'Coffee cups of three different sizes (identified as size 1, size 2 and size 3 cups) are produced in factories under ACM (Association of Cup Makers) and are sold in various packages. Each type of package is identified by three positive integers (S1, S2, S3) where Si (1 <=i <= 3) denotes the number of size i cups included in the package. There is no package with S1 = S2 = S3.\r\n\r\n\r\nBut recently it has been discovered that there is a great demand for packages containing equal number cups of all three sizes. So, as an emergency step to meet the demand ACM has decided to unpack the cups from some of the packages stored in its (unlimited) stock of unsold products and repack them in packages having equal number of cups of all three sizes. For example, suppose ACM has the following four types of packages in its stock: (1, 2, 3), (1, 11, 5), (9, 4, 3) and (2, 3, 2). So, one can unpack three (1, 2, 3) packages, one (9, 4, 3) package and two (2, 3, 2) packages and repack the cups to produce sixteen (1, 1, 1) packages. One can even produce eight (2, 2, 2) packages or four (4, 4, 4) packages or two (8, 8, 8) packages or one (16, 16, 16) package or even different combination of packages each containing equal number of size 1, size 2 and size 3 cups. Note that all the unpacked cups are used to produce the new packages, i.e., no unpacked cup is wasted.\r\n\r\n\r\nACM has hired you to write a program that will decide whether it is possible to produce packages containing equal number of all three types of cups using all the cups that can be found by unpacking any combination of existing packages in the stock.\r\n', '4 <br/>\r\n1 2 3 <br/>\r\n1 11 5 <br/>\r\n9 4 3 <br/>\r\n2 3 2 <br/>\r\n4 <br/>\r\n1 3 3 <br/>\r\n1 11 5 <br/>\r\n9 4 3 <br/>\r\n2 3 2 <br/>\r\n0 <br/>\r\n', '4 \r\n1 3 3 \r\n9 11 2 \r\n1 5 5 \r\n2 0 \r\n0\r\n', 'Yes <br/>\r\nNo', 'No', 10, 2, 'The input may contain multiple test cases. Each test case begins with a line containing an integer N (3 <= N <= 1000) indicating the number of different types of packages that can be found in the stock. Each of the next N lines contains three positive integers denoting respectively the number of size 1, size 2 and size 3 cups in a package. No two packages in a test case will have the same specification.\r\n           \r\nA test case containing a zero for N in the first line terminates the input.\r\n', 'For each test case in the input print a line containing "Yes" if packages can be produced as desired, print "No" otherwise.', 'Temp'),
(23, 'THE CRAZY LOVERS', 'Everyone loves to take shortcuts. It makes life simpler. But some people always love to go round the way and land up in troubles!!! This can often be highly annoying for their friends.<br/>\r\nRomeo has this kind of problem. When he has to go from one point to another, he always chooses the longest path. Romeo girlfriend, Juliet, has understood the nature of the problem. Juliet thinks that with the help of her friend she might be able to calculate the time that Romeo is going to take to reach the party. That way she could have other guests invited, when Romeo reach.<br/><br/>\r\n\r\nYour goal is to help Juliet develop a program that computes the length of the longest path that can be constructed in a given graph from a given starting point (RomeoÃ¢â‚¬â„¢s residence). You can assume that the graph has no cycles (there is no path from any node to itself), so Romeo will reach his destination in a finite time. In the same line of reasoning, nodes are not considered directly connected to themselves.<br/>\r\n', '2<br/>\r\n1<br/>\r\n1 2<br/>\r\n0 0<br/>\r\n5<br/>\r\n3<br/>\r\n1 2<br/>\r\n3 5<br/>\r\n3 1<br/>\r\n2 4<br/>\r\n4 5<br/>\r\n0 0<br/>\r\n0<br/>\r\n<br/>', '2\r\n1\r\n1 2\r\n0 0\r\n5\r\n3\r\n1 2\r\n3 5\r\n3 1\r\n2 4\r\n4 5\r\n0 0\r\n5\r\n5\r\n5 1\r\n5 2\r\n5 3\r\n5 4\r\n4 1\r\n4 2\r\n0 0\r\n0\r\n', 'Case 1: The longest path from 1 has length 1, finishing at 2.<br/>\r\n<br/>\r\nCase 2: The longest path from 3 has length 4, finishing at 5.<br/>\r\n', 'Case 1: The longest path from 1 has length 1, finishing at 2.\r\n\r\nCase 2: The longest path from 3 has length 4, finishing at 5.\r\n\r\nCase 3: The longest path from 5 has length 2, finishing at 1.\r\n', 15, 3, 'The input consists of a number of cases. The first line on each case contains a positive number n (1<n<=100) that specifies the number of points that Romeo might visit (i.e., the number of nodes in the graph).\r\nA value of n = 0 indicates the end of the input.<br/><br/>\r\n\r\nAfter this, a second number s is provided, indicating the starting point in RomeoÃ¢â‚¬â„¢s journey (1<=s<=n). Then, you are given a list of pairs of places p and q, one pair per line, with the places on each line separated by white-space. The pair ``p q" indicates that Romeo can visit q after p.<br/>\r\nA pair of zeros (``0 0") indicates the end of the case.<br/><br/>\r\n\r\nAs mentioned before, you can assume that the graphs provided will not be cyclic.<br/><br/>\r\n', 'For each test case you have to find the length of the longest path that begins at the starting place. You also have to print the number of the final place of such longest path. If there are several paths of maximum length, print the final place with smallest number. Print a new line after each test case.', 'Temp'),
(24, 'Factorial Function', 'The factorial function, n! is defined as follows for all non-negative integers n:<br/>\r\n0! = 1<br/>\r\nn! = n Ã— (n âˆ’ 1)! (n > 0)<br/>\r\nWe say that a divides b if there exists an integer k such that k Ã— a = b\r\n', '3<br/>\r\n6 9<br/>\r\n6 27<br/>\r\n20 10000<br/>\r\n', '5\r\n6 9\r\n6 27\r\n20 10000\r\n20 100000\r\n1000 1009\r\n', '9 divides 6!<br/>\r\n27 does not divide 6!<br/>\r\n10000 divides 20!<br/>', '9 divides 6!\r\n27 does not divide 6!\r\n10000 divides 20!\r\n100000 does not divide 20!\r\n1009 does not divide 1000!\r\n', 5, 1, 'First line specify number of test case.The input to your program consists of several lines, each containing two non-negative\r\nintegers, n and m.\r\n', 'For each input line, output a line stating whether or not m divides n!, in the format\r\nshown below.\r\n', 'Temp'),
(25, 'Addition', 'Children are taught to add multi-digit numbers from right to left, one digit at a time.\r\nMany find the â€œcarryâ€ operation, where a 1 is carried from one digit position to the\r\nnext, to be a significant challenge. Your job is to count the number of carry operations\r\nfor each of a set of addition problems so that educators may assess their difficulty.\r\n\r\n', '123 456<br/>\r\n555 555<br/>\r\n0 0<br/>', '123 456\r\n555 555\r\n123 594\r\n0 0\r\n', 'No carry operation.<br/>\r\n3 carry operations.<br/>\r\n', 'No carry operation.\r\n3 carry operations.\r\n1 carry operation.\r\n', 5, 1, 'Each line of input contains two unsigned integers less than 10 digits. The last line of\r\ninput contains â€œ0 0â€.', 'For each line of input except the last, compute the number of carry operations that\r\nresult from adding the two numbers and print them in the format shown below.\r\n', 'Temp'),
(26, 'HINDI NUMERAL SYSTEM', 'In hindi, the numbers are written as karod(crore)(10000000),lakh(100000),hajar(1000),sau(100) while \r\nexpanding and converting to text. You are going to write a program to convert a given number to text with them.', '23764 ', '4585989', '23 hajar 7 shata 64 sau', '45 lakh 85 hazar 98 sau 9', 5, 1, 'The input file may contain several test cases.Each case will contain a positive number <=999999999999.', 'For each case of input, you have to output a line starting with the case no with two digits adjustment followed by the converted text.', 'Temp'),
(27, 'Little Masters', 'Bangladesh whitewashed New Zealand in the three-match one day\r\ninternational series defeating the visitors by four wickets in the last\r\nand final match in Narayanganj. The Tigers scored 309 runs in\r\n49.2 overs for the loss of six wickets at the Khan Shaheb Osman\r\nAli Stadium in Fatullah .The most remarkable was the performance\r\nfrom the batsman of tiger side. Mominul, Nasir, Naeem, Mushfiq\r\nall showed tremendous batting performance. People call them little\r\nmasters. They are clever enough to find a quick boundary. Here we\r\nhave to do a little task for our busy little masters. We have to find\r\nout the length of the shortest and longest boundary distance from\r\nthe batsman. We know the radius of the circular stadium and the\r\nposition of the batsman.\r\nCenter of the stadium is always the origin (0, 0).\r\nBoundary means the perimeter of the circular field.\r\n', '2\r\n0 0 100\r\n3 4 10', '3\r\n0 0 100\r\n3 4 10\r\n5 0 5\r\n', '100.00 100.00\r\n5.00 15.00', '100.00 100.00\r\n5.00 15.00\r\n0.00 10.00', 15, 3, 'Input starts with an integer T (â‰¤ 100), denoting the number of test cases. Each case starts with a line\r\ncontaining three integers x, y, r (0 â‰¤ x, y, r â‰¤ 1000). (x, y) denotes the coordinate of the batsman.\r\nAnd r denotes the radius of the stadium. You can safely assume that coordinate of the batsman will\r\nnot be out of the stadium.', 'For each case, print the shortest and longest boundary distance. Show exactly 2 digits after decimal\r\npoint, properly rounded. See the samples for exact formatting', 'Temp'),
(28, 'CRICKET SERIES', 'India is to play a number of Test and One day series in the year 2014-15.\r\nAt first, the number of series that India will play in the year 2014-15 is inputted from the user.\r\nNow for each series the number of matches is inputted. Now a string denoting the result of each matches is inputted.\r\nW- India win\r\nL- India lose\r\nD-Draw/Abandoned\r\nT-Tie\r\nNow for each series, the result of the series is to be printed.', '3<br/>\r\n4<br/>\r\nWWDL<br/>\r\n3<br/>\r\nWDL<br/>\r\n4<br/>\r\nLLDL<br/>', '2\r\n5\r\nWWWLL\r\n5\r\nWWTLL', '1.India won<br/>\r\n2.Draw series<br/>\r\n3.India lose<br/>', '1.India win\r\n2.Draw series', 5, 1, 'At first the number of series that India will play in the season is to be inputted\r\nThen the No of matches in each series is to be inputted followed by the result of each matches in WDL format', 'The result of each series played by India in the serial order is to be printed', 'Temp'),
(29, 'Dividing UP', 'Marsha and Bill own a collection of marbles. They want to split the collection among themselves so that both receive an equal share of the marbles. This would be easy if all the marbles had the same value, because then they could just split the collection in half. But unfortunately, some of the marbles are larger, or more beautiful than others. So, Marsha and Bill start by assigning a value, a natural number between one and six, to each marble. Now they want to divide the marbles so that each of them gets the same total value.\r\nUnfortunately, they realize that it might be impossible to divide the marbles in this way (even if the total value of all marbles is even). For example, if there are one marble of value 1, one of value 3 and two of value 4, then they cannot be split into sets of equal value. So, they ask you to write a program that checks whether there is a fair partition of the marbles.\r\n', '1 0 1 2 0 0 <br/>\r\n0 0 0 0 0 0\r\n', '1 0 1 2 0 0\r\n1 0 0 0 1 1\r\n0 0 0 0 0 0\r\n', 'Collection #1:<br/> \r\nCANT BE DIVIDED<br/>\r\n', 'Collection #1:\r\nCANT BE DIVIDED\r\n\r\nCollection #2:\r\nCAN BE DIVIDED\r\n', 10, 2, 'Each line in the input file describes one collection of marbles to be divided. The lines consist of six non-negative integers n1...n6, where ni is the number of marbles of value i. So, the example from above would be described by the input-line 1 0 1 2 0 0. The maximum total number of marbles will be 20000.\r\nThe last line of the input file will be - 0 0 0 0 0 0- do not process this line.\r\n', 'For each collection, output Collection #k:, where k is the number of the test case, and then either CAN BE DIVIDED or CANT BE DIVIDED\r\nOutput a blank line after each test case.\r\n', 'Temp'),
(30, 'Flag', 'Teering is a little boy. He is trying to draw the national flag of Bangladesh. Being smart he knows he has to maintain the correct ratio and measurement while drawing the flag. You know the rules of drawing the national flag, don''t you? If not, no worries, Teering is here to help you:\r\n<br/><br/>\r\nThe national flag of Bangladesh consist of a green rectangle with a red circle inside it. The ratio of the length and width of the rectangle is 100 : 60 (i.e. if the length is 100 units then the width will be 60 units). The radius of the circle is 20% of the length (i.e. if the length is 100 units then the radius of the circle will be 20 units). To get the center of the circle you need to draw a horizontal line dividing the width in equal portion and draw a vertical line dividing the length in 45 : 55 ratio (i.e. if the length of the rectangle is 100 then 45 units will be in left and 55 units will be on the right side of the line). The crossing of the two lines will be the center of the circle.<br/><br/>\r\nNow Teering has started to draw a flag. He has already drawn the circle of radius R centered at the origin in a 2D co-ordinate system. Now he needs to determine the corner of the rectangle so that he can join them to complete the flag. Can you help him?', '1<br/>\r\n20<br/>', '2\r\n20\r\n100', 'Case 1:<br/>\r\n-45 30<br/>\r\n55 30<br/>\r\n55 -30<br/>\r\n-45 -30<br/>', 'Case 1:\r\n-45 30\r\n55 30\r\n55 -30\r\n-45 -30\r\nCase 2:\r\n-225 150\r\n275 150\r\n275 -150\r\n-225 -150', 5, 1, 'The first line of input will contain an integer T (T < 101) denoting the number of test cases. Each of the following T lines will contain an integer R (R < 1001) each denoting the radius of the circle.', 'For each input output five lines. The first line will contain the case number. The following four lines will denote the upper left, upper right, lower right and lower left coordinates of the rectangle for the flag respectively. You have to print x coordinate and y coordinate separated by space in each line. You may assume that input is given in such that the corners will always be in integer coordinates. See sample input output for details.', 'Temp'),
(31, 'Calc', 'You are an employee of a company which produces calculators. Your company is developing an outstanding new calculator, and you are developing the software of that new calculator. This calculator is intended for people that would like to save intermediate values in the memory for future use. For this reason, this new calculator has space for 26 values in its memory, named a to z. Those values are stored with double precision.<br/>\r\n<br/>\r\nFor simplicity, here we will consider only the four basic operations, sum, minus, multiply and divide (+ - * /). Also, expressions can be grouped with parenthesis. You should consider the precedence of operations, with multiplication and division first, then addition and subtraction. Also, only integer numbers and the letters a to z will appear on the expression, along with the symbols of the operations, the parenthesis and the equal sign for attribution.', 'x=10<br/>\r\nx<br/>\r\nx+10<br/>\r\nx/5<br/>\r\nx/2<br/>\r\nx/3<br/>\r\ny=5/3<br/>\r\ny<br/>\r\nx*y<br/>\r\n0<br/>\r\n<br/>', 'x=10\r\nx\r\nx+10\r\nx/5\r\nx/2\r\nx/3\r\ny=5/3\r\ny\r\nx*y\r\nx-y\r\n0', '10.00<br/>\r\n20.00<br/>\r\n2.00<br/>\r\n5.00<br/>\r\n3.33<br/>\r\n1.67<br/>\r\n16.67<br/><br/>', '10.00\r\n20.00\r\n2.00\r\n5.00\r\n3.33\r\n1.67\r\n16.67\r\n8.33', 15, 3, 'The input consists of an undetermined number of lines, with one expression per line. One expression can be an attribution or a question. If the expression is an attribution it will begin with X=, where X is the letter representing the memory space and a ? X ? z. If the expression is not an attribution expression, then it is a question. There will be no blank spaces in the expression. You will only produce output for the questions.<br/><br/>\r\n\r\nThe input will end with 0', 'For each question, print it''s evaluated value on a line by itself. Print the result rounded to two decimal places. See sample input/output for the exact format.<br/>', 'Temp'),
(33, '2 The 9', 'A well-known trick to know if an integer N is a multiple of nine is to compute the sum S of its digits. If S is a multiple of nine, then so is N. This is a recursive test, and the depth of the recursion needed to obtain the answer on N is called the 9-degree of N.<br/>\r\n<br/>\r\nYour job is, given a positive number N, determine if it is a multiple of nine and,if it is, its 9-degree.<br/>', '999999999999999999999<br/>\r\n9<br/>\r\n0<br/>', '999999999999999999999\r\n9\r\n9999999999999999999999999999998\r\n0', '999999999999999999999 is a multiple of 9 and has 9-degree 3.<br/>\r\n9 is a multiple of 9 and has 9-degree 1.<br/>', '999999999999999999999 is a multiple of 9 and has 9-degree 3.\r\n9 is a multiple of 9 and has 9-degree 1.\r\n9999999999999999999999999999998 is not a multiple of 9.', 15, 3, 'The input is a file such that each line contains a positive number. A line containing the number 0 is the end of the input. The given numbers can contain up to 1000 digits.', 'The output of the program shall indicate, for each input number, if it is a multiple of nine, and in case it is, the value of its nine-degree. See the sample output for an example of the expected formatting of the output.', 'Temp'),
(34, 'Seven Seas', 'Seven Seas is a nice game where you are the captain of a battle ship. You are in the middle of the ocean and there are some enemy ships trying to catch you. Your mission is to run away from them. Destroy the enemies if you can!<br/><br/>\r\n\r\nThe game is played on a 9x8 board and you can move in all the 8 directions, one step each time. You move first, then the enemy ships move. The enemy ships are pretty dumb, so that they will always move to the closest position they can get to you, even if that position will destroy their ship. A ship is destroyed if it moves to a cell that contais a rock. If two enemy ships move to the same cell they are also destroyed and their remains will stay in that cell so that if another ship try to move there it will be destroyed too.<br/><br/>\r\n\r\nIf an enemy ship reaches your ship, you are dead and the game is over.<br/><br/>', '2<br/>\r\n........<br/>\r\n.E.#....<br/>\r\n...E....<br/>\r\n..#.....<br/>\r\n........<br/>\r\n........<br/>\r\n..S.....<br/>\r\n........<br/>\r\n........<br/>\r\n<br/>\r\n........<br/>\r\n.E.E....<br/>\r\n...S....<br/>\r\n.E..E...<br/>\r\n........<br/>\r\n........<br/>\r\n........<br/>\r\n........<br/>\r\n........<br/><br/>', '3\r\n........\r\n.E.#....\r\n...E....\r\n..#.....\r\n........\r\n........\r\n..S.....\r\n........\r\n........\r\n\r\n........\r\n.E.E....\r\n...S....\r\n.E..E...\r\n........\r\n........\r\n........\r\n........\r\n........\r\n\r\nE......#\r\n........\r\n........\r\n........\r\n........\r\n........\r\n........\r\n.......S\r\n#.......', 'I am the king of the Seven Seas!<br/>\r\nOh no! I am a dead man!<br/>', 'I am the king of the Seven Seas!\r\nOh no! I am a dead man!\r\nOh no! I am a dead man!', 15, 3, 'The first line of the input contains the number of scenarios. Each scenarion consists of a 9x8 board of charachters. Your ship is represented by a S on the board and the enemy ships are represented by a E. The rocks are represented by a # and the . represents the sea. See the sample input to see the specific input format.<br/>\r\n<br/>\r\nThere will be at least one and at most nine enemy ships. There will be an empty line between two scenarios<br/>', 'For each scenario you must find out if it is possible to destroy all the enemy ships in less than 10 steps. If that is the case, you must print one line containing the string: I am the king of the Seven Seas!. Otherwise, you must print one line with the string: Oh no! I am a dead man!.<br/>', 'Temp'),
(35, ' Gleaming the Cubes ', 'As chief engineer of the Starship Interprize, the task of repairing the hyperstellar, cubic, transwarped-out software has fallen on your shoulders. Simply put, you must compute the volume of the intersection of anywhere from 2 to 1000 cubes.', '2<br/>\r\n0 0 0 10<br/>\r\n9 1 1 5<br/>\r\n0<br/>', '2\r\n0 0 0 10\r\n9 1 1 5\r\n3\r\n0 0 0 10\r\n9 1 1 5\r\n8 2 2 3\r\n0', '25<br/>', '25\r\n9', 5, 1, 'The input data file consists of several sets of cubes for which the volume of their intersections must be computed. The first line of the data file contains a number (from 2 to 1000) which indicates the number of cubes which follow, one cube per line. Each line which describes a cube contains four integers. The first three integers are the x, y and z coordinates of the corner of a cube, and the fourth integer is the positive distance which the cube extends in each of the three directions (parallel to the x, y, and z axes) from that corner.\r\n\r\n', 'Following the data for the first set of cubes will be a number which indicates how many cubes are in a second set, followed by the cube descriptions for the second set, again one per line. Following this will be a third set, and so on. Your program should continue to process sets of cubes, outputting the volume of their intersections to the output file, one set per line, until a zero is read for the number of cubes.\r\n<br/><br/><br/><br/><br/>\r\n\r\nNote that the data file will always contain at least one set of cubes, and every set will contain at least 2 and at most 1000 cubes. For any given set of cubes, the volume of their intersections will not exceed 1,000,000 units.\r\n<br/><br/><br/>\r\nData file is the stdin and stdout.No need to open file.', 'Temp'),
(37, 'Fibinary number', 'The standard interpretation of the binary number 1010 is 8 + 2 = 10. An alternate way to view the sequence 1010 is to use Fibonacci numbers as bases instead of powers of two. For this problem, the terms of the Fibonacci sequence are: 1, 2, 3, 5, 8, 13, 21 \r\nWhere each term is the sum of the two preceding terms (note that there is only one 1 in the sequence as defined here). Using this scheme, the sequence 1010 could be interpreted as  1.5 + 0.3 + 1.2 + 0.1 = 7. This representation is called a Fibinary number.\r\n<br/><br/>\r\nNote that there is not always a unique Fibinary representation of every number. For example the number 10 could be represented as either 8 + 2 (10010) or as 5 + 3 + 2 (1110). To make the Fibinary representations unique, larger Fibonacci terms must always be used whenever possible (i.e. disallow 2 adjacent 1s). Applying this rule to the number 10, means that 10 would be represented as 8+2 (10010).', '10010<br/>\r\n1<br/>\r\n<br/>\r\n10000<br/>\r\n1000<br/>\r\n<br/>\r\n0 0<br/>', '10010\r\n1\r\n\r\n10000\r\n1000\r\n\r\n10000\r\n10000\r\n\r\n0 0', '10100<br/>\r\n100000<br/>', '10100\r\n100000\r\n100100', 10, 2, 'Write a program that takes two valid Fibinary numbers and prints the sum in Fibinary form. These numbers will have at most 100 digits.\r\n0 0 will end the cases.<br/><br/>', NULL, 'Temp'),
(38, 'Lucky Number', 'Lucky numbers are defined by a variation of the well-known sieve of Eratosthenes. Beginning with the natural numbers strike out all even ones, leaving the odd numbers 1, 3, 5, 7, 9, 11, 13, ... The second number is 3, next strike out every third number, leaving 1, 3, 7, 9, 13, ... The third number is 7, next strike out every seventh number and continue this process infinite number of times. The numbers surviving are called lucky numbers. The first few lucky numbers are:<br/>\r\n<br/>\r\n            1, 3, 7, 9, 13, 15, 21, 25, 31, 33, â€¦ â€¦<br/>\r\n<br/>\r\nIn this problem your task is to test whether a number can be written as the sum of two lucky numbers.<br/>', '1<br/>\r\n11<br/>', '3\r\n11\r\n12\r\n64', '11 is not the sum of two luckies!<br/>', '11 is not the sum of two luckies!\r\n12 is the sum of 3 and 9.\r\n64 is the sum of 31 and 33', 10, 2, 'First number specify the number of test case followed by numbers.', 'For each line of input produce one line of output. This line should be of one of the following types depending on whether n is expressible as the sum of two lucky numbers.<br/>\r\n<br/><br/>\r\n     n is not the sum of two luckies!<br/>\r\n     n is the sum of L1 and L2.<br/>\r\n<br/>', 'Temp'),
(39, 'Cards', 'Given is an ordered deck of n cards numbered 1 to n with card 1 at the top and card n at the bottom. The following operation is performed as long as there are at least two cards in the deck:<br/>\r\nThrow away the top card and move the card that is now on the top of the deck to the bottom of the deck.<br/>\r\n<br/>\r\nYour task is to find the last, remaining card.<br/>\r\n<br/>\r\nEach line of input (except the last) contains a positive number n â‰¤ 500000. The last line contains 0 and this line should not be processed. For each number from input produce one line of output giving the last remaining card. Input will not contain more than 500000 lines.<br/>', '7<br/>\r\n19<br/>\r\n0<br/>', '7\r\n19\r\n10\r\n6\r\n0', '6<br/>\r\n6<br/>', '6\r\n6\r\n4\r\n4', 10, 2, 'Nil', 'Nil', 'Temp'),
(40, 'Distinct Subsequences', 'A subsequence of a given sequence is just the given sequence with some elements (possibly none) left out. Formally, given a sequenceX = x1x2.....xm, another sequence Z = z1z2.....zk is a subsequence of X if there exists a strictly increasing sequence <i1, i2, , ik>1 of indices of X such that for all j = 1, 2, â€¦, k, we have xij = zj. For example, Z = bcdb is a subsequence of X = abcbdab with corresponding index sequence < 2, 3, 5, 7 >.\r\nIn this problem your job is to write a program that counts the number of occurrences of Z in X as a subsequence such that each has a distinct index sequence.\r\n', '1 <br/>\r\nbabgbag<br/>\r\nbag<br/>\r\n', '2\r\nbabgbag\r\nbag\r\nrabbbit\r\nrabbit\r\n', '5', '5\r\n3', 10, 2, 'The first line of the input contains an integer N indicating the number of test cases to follow.\r\nThe first line of each test case contains a string X, composed entirely of lowercase alphabetic characters and having length no greater than 10,000. The second line contains another string Z having length no greater than 100 and also composed of only lowercase alphabetic characters. Be assured that neither Z nor any prefix or suffix of Z will have more than 10100 distinct occurrences in X as a subsequence.\r\n', 'For each test case in the input output the number of distinct occurrences of Z in X as a subsequence. Output for each input set must be on a separate line.', 'Temp'),
(41, 'CODED MESSAGES', 'â€˜Rose is about to be in serious troubleâ€™, Kenâ€™s mind registered quickly as he watched the  men at one end of the dance floor pushing their way determinedly towards the centre, towards his CIA partner. Both of them were in an undercover operation which needed her to be dancing in the very arms of the man they were after, Mr. Theodore Collins. Ken moved swiftly around the aerial walking path above the floor sending her an alert message. Upon reaching the exit, he turned and saw Mr. Collins laughing mildly and taking the phone from the hands of a startled Rose. One look at the message was all it was needed to arouse suspicion, as Ken had feared. Rose acted quickly taking her phone back, mumbling a sorry and barely managed to get out before getting caught. \r\nAs they were driving away to safety Ken thought of finding a less obvious way to send and analyze secret coded messages.\r\nYour task is to write a program to do so by performing a simple analysis of the message. \r\n', '3 <br/>\r\nThis is a test.<br/>\r\nCount me 1 2 3 4 5.<br/>\r\nWow!!!  Is this question easy?<br/>\r\n', '1\r\nNo ClUB better than Man Utd \r\n', 'S 7<br/>\r\nT 6<br/>\r\nI 5<br/>\r\nE 4<br/>\r\nD 3<br/>\r\nA 2<br/>\r\nH 2<br/>\r\nN 2<br/>\r\nU 2<br/>\r\nW 2<br/>\r\nC 1<br/>\r\nM 1<br/>\r\nQ 1<br/>\r\nY 1<br/>\r\n', 'T 4\r\nN 3\r\nA 2\r\nB 2\r\nE 2\r\nU 2\r\nC 1\r\nD 1\r\nH 1\r\nL 1\r\nM 1\r\nO 1\r\nR 1\r\n\r\n\r\n\r\n\r\n\r\n', 10, 2, 'The first line of input will be the number of lines of message, n. The next n lines will contain zero or more characters (possibly including white space). This is the message to be analyzed.', 'Each line of output contains a single uppercase letter, followed by a single space, then followed by a positive decimal integer. The integer indicates how many times the corresponding letter appears in the input text. Upper and lower case letters were to be considered the same. No other characters must be counted. The output must be sorted in descending count order; that is the most frequent letter is on the first output line, and the last line of output indicates the least frequent letter. If two letters have the same frequency, then the letter which counts first in the alphabet must appear first in the output. If a letter does not appear in text, then that letter must not appear in the output.\r\n', 'Temp');

-- --------------------------------------------------------

--
-- Table structure for table `user_details`
--

DROP TABLE IF EXISTS `user_details`;
CREATE TABLE IF NOT EXISTS `user_details` (
  `full_name` varchar(30) CHARACTER SET ascii NOT NULL,
  `email` varchar(30) NOT NULL,
  `password` varchar(32) NOT NULL,
  `phone` varchar(15) NOT NULL,
  `college` text,
  `marks` int(5) NOT NULL DEFAULT '0',
  `level` int(2) NOT NULL DEFAULT '1',
  `current_question` varchar(5) NOT NULL DEFAULT '0',
  PRIMARY KEY (`email`),
  UNIQUE KEY `phone` (`phone`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `user_details`
--

INSERT INTO `user_details` (`full_name`, `email`, `password`, `phone`, `college`, `marks`, `level`, `current_question`) VALUES
('', '', 'aa7283a0b124df5b33348b5073dcc9f5', '', '', 0, 1, '0'),
('Stenal P Jolly', 'stenalpjolly@gmail.com', 'aa7283a0b124df5b33348b5073dcc9f5', '8547915429', 'M A College of Engineering', 0, 1, '0');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
